[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["php84", "php84Extensions.mbstring", "php84Extensions.xml", "php84Extensions.tokenizer", "php84Extensions.pdo", "php84Extensions.pdo_mysql", "php84Extensions.curl", "php84Extensions.zip", "php84Extensions.gd", "composer"]

[build.nixpacksPlan.phases.build]
cmds = ["composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-gd"]

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"